apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-controller-manager
  namespace: test-capo
spec:
  selector:
    matchLabels:
      control-plane: ansible-controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: ansible-controller-manager
    spec:
      containers:
        - command:
            - /usr/bin/launcher-ansible
          args:
            - --leader-elect
          image: hub.easystack.cn/captain/launcher:dev
          name: manager
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          # TODO(user): Configure the resources accordingly based on the project requirements.
          # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            limits:
              cpu: 1000m
              memory: 4096Mi
            requests:
              cpu: 1000m
              memory: 4096Mi
      terminationGracePeriodSeconds: 10
      serviceAccountName: ansible-plan-sa