# permissions for end users to view clusteroperationsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusteroperationset-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: easystack-eks-op
    app.kubernetes.io/part-of: easystack-eks-op
    app.kubernetes.io/managed-by: kustomize
  name: clusteroperationset-viewer-role
rules:
- apiGroups:
  - easystack.com
  resources:
  - clusteroperationsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - easystack.com
  resources:
  - clusteroperationsets/status
  verbs:
  - get
