apiVersion: ecns.easystack.com/v1
kind: Plan
metadata:
  labels:
    app.kubernetes.io/name: plan
    app.kubernetes.io/instance: plan-sample
    app.kubernetes.io/part-of: easystack-eks-op
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: easystack-eks-op
  name: plan-sample
  namespace: mj
spec:
  mode: "new"
  k8sVersion: "v1.26.4-es"
  support_python3: false
  lb_enable: false
  cluster_name: "test2"
  ssh_key: "binshan"
  use_float_ip: false
  node_cidr: "10.6.0.0/24"
  other_ansible_opts:
    "cloud_master_vip": "172.35.0.2"
    "registry_ip": "172.35.0.73"
    "webhook_enabled": "false"
    "flannel_interface": "ens3"
    "keepalived_interface": "ens3"
  need_keep_alive:
    - "master"
    - "ingress"
    - "ingress1"
  need_load_balancer:
    - "ingress"
    - "master"
    - "ingress1"
  machine_sets:
    - name: "test-master"
      role: "master"
      number: 3
      infras:
        - uid: "7d2d"
          availability_zone: "default-az"
          volumes:
            - volume_type: "hdd"
              volume_size: 150
              index: 1
            - volume_type: "hdd"
              volume_size: 10
              index: 2
            - volume_type: "hdd"
              volume_size: 5
              index: 3
          image: "kylin-x86-raw-0816"
          flavor: "8C-8G"
          replica: 2
        - uid: "7d3d"
          availability_zone: "default-az"
          volumes:
            - volume_type: "hdd"
              volume_size: 150
              index: 1
            - volume_type: "hdd"
              volume_size: 5
              index: 2
            - volume_type: "hdd"
              volume_size: 5
              index: 3
          image: "kylin-x86-raw-0816"
          flavor: "8C-8G"
          replica: 1
    - name: "test-node"
      number: 1
      role: "node"
      infras:
        - uid: "bb85"
          availability_zone: "default-az"
          volumes:
            - volume_type: "hdd"
              volume_size: 150
              index: 1
            - volume_type: "hdd"
              volume_size: 10
              index: 2
            - volume_type: "hdd"
              volume_size: 5
              index: 3
          image: "kylin-x86-raw-0816"
          flavor: "8C-8G"
          replica: 1
    - name: "test-ingress"
      number: 1
      role: "ingress"
      infras:
        - uid: "bb90"
          availability_zone: "default-az"
          volumes:
            - volume_type: "hdd"
              volume_size: 150
              index: 1
            - volume_type: "hdd"
              volume_size: 10
              index: 2
            - volume_type: "hdd"
              volume_size: 5
              index: 3
          image: "kylin-x86-raw-0816"
          flavor: "8C-8G"
          replica: 1
    - name: "test-etcd"
      number: 3
      role: "etcd"
      infras:
        - uid: "bb110"
          availability_zone: "default-az"
          volumes:
            - volume_type: "hdd"
              volume_size: 150
              index: 1
            - volume_type: "hdd"
              volume_size: 10
              index: 2
            - volume_type: "hdd"
              volume_size: 5
              index: 3
          image: "kylin-x86-raw-0816"
          flavor: "8C-8G"
          replica: 3
    - name: "test-prometheus"
      number: 2
      role: "prometheus"
      infras:
        - uid: "bb95"
          availability_zone: "default-az"
          volumes:
            - volume_type: "hdd"
              volume_size: 150
              index: 1
            - volume_type: "hdd"
              volume_size: 10
              index: 2
            - volume_type: "hdd"
              volume_size: 5
              index: 3
          image: "kylin-x86-raw-0816"
          flavor: "8C-8G"
          replica: 2
    - name: "test-gpu"
      number: 0
      role: "nvidia-accelerator"
      infras:
        - uid: "bb105"
          availability_zone: "default-az"
          volumes:
            - volume_type: "hdd"
              volume_size: 150
              index: 1
            - volume_type: "hdd"
              volume_size: 10
              index: 2
            - volume_type: "hdd"
              volume_size: 5
              index: 3
          image: "eks-kylin-gpu-accelerated-x86_64"
          flavor: "8C-8G"
          replica: 0
  monitor:
    pvc_type: "cinder"
    pvc_cap: "10"
    auto_clear_days: "7d"
  cni_type: "flannel"
  pod_cidr: "10.232.0.0/14"
  svc_cidr: "10.222.0.0/16"
  maxRetryTime: 5
  ansible_plan_auto: true
  user:
    auth_url: "http://keystone.openstack.svc.cluster.local/v3"
    token: "gAAAAABlEPaq0BmJYzVMUG0u_QAjhTPb_wkyl-rLhB3NdQbVGPSHslAlPreea0FdxG4G7lVX6mLJTtWoaE4wYD58t_IGTq06ybuxraQ16ROtpfXGXmgbhg0M4QfnKkYgvr5mgbAWz3Dq83Lq5QMlnCHBM6uQoKbQnI3Hhlt1TE_f9i0BWFjr6Os"
    region: "RegionOne"





  # TODO(user): Add fields here
