apiVersion: ecns.easystack.com/v1
kind: Plan
metadata:
  labels:
    app.kubernetes.io/name: plan
    app.kubernetes.io/instance: plan-sample
    app.kubernetes.io/part-of: easystack-eks-op
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: easystack-eks-op
  name: plan-sample
  namespace: test-capo
spec:
  mode: "new"
  k8sVersion: "1.20.14"
  support_python3: false
  lb_enable: true
  cluster_name: "test1"
  ssh_key: "binshan"
  use_float_ip: true
  node_cidr: "10.6.0.0/24"
  need_keep_alive:
    - "master"
    - "ingress"
    - "ingress1"
  need_load_balancer:
    - "ingress"
    - "master"
    - "ingress1"
  machine_sets:
    - name: "test-master"
      role: "master"
      number: 3
      infras:
        - uid: "7d2d"
          availability_zone: "default-az"
          volumes:
            - volume_type: "hdd"
              volume_size: 20
              index: 1
            - volume_type: "hdd"
              volume_size: 10
              index: 2
            - volume_type: "hdd"
              volume_size: 5
              index: 3
          image: "centos-qga"
          flavor: "2C-4G"
          replica: 1
        - uid: "7d3d"
          availability_zone: "default-az"
          volumes:
            - volume_type: "hdd"
              volume_size: 30
              index: 1
            - volume_type: "hdd"
              volume_size: 5
              index: 2
            - volume_type: "hdd"
              volume_size: 5
              index: 3
          image: "centos-qga"
          flavor: "2C-4G"
          replica: 2
    - name: "test-node"
      number: 2
      role: "node"
      infras:
        - uid: "bb85"
          availability_zone: "default-az"
          volumes:
            - volume_type: "hdd"
              volume_size: 20
              index: 1
            - volume_type: "hdd"
              volume_size: 10
              index: 2
            - volume_type: "hdd"
              volume_size: 5
              index: 3
          image: "centos-qga"
          flavor: "2C-4G"
          replica: 2
    - name: "test-ingress"
      number: 1
      role: "ingress"
      infras:
        - uid: "bb90"
          availability_zone: "default-az"
          volumes:
            - volume_type: "hdd"
              volume_size: 20
              index: 1
            - volume_type: "hdd"
              volume_size: 10
              index: 2
            - volume_type: "hdd"
              volume_size: 5
              index: 3
          image: "centos-qga"
          flavor: "2C-4G"
          replica: 1
    - name: "test-ingress"
      number: 1
      role: "ingress1"
      infras:
        - uid: "bb95"
          availability_zone: "default-az"
          volumes:
            - volume_type: "hdd"
              volume_size: 20
              index: 1
            - volume_type: "hdd"
              volume_size: 10
              index: 2
            - volume_type: "hdd"
              volume_size: 5
              index: 3
          image: "centos-qga"
          flavor: "2C-4G"
          replica: 1
  monitor:
    pvc_type: "hdd"
    pvc_cap: "10"
    auto_clear_days: "7"
  cni_type: "flannel"
  pod_cidr: "10.232.0.0/14"
  svc_cidr: "10.222.0.0/16"
  ansible_plan_auto: false
  user:
    auth_url: "http://keystone.openstack.svc.cluster.local/v3"
    token: "gAAAAABkzL7AFJullhmndUZ3qf_r8KpA4sSyUdgH0i5TiPm9skBB4gihUFqhq_h-c-RLAiMFZF_6zFMAYdcrVv6ClinUX-GRikFr0mnQNf44XpUZ92FdeVYylKFHcWkvnO2XRA9uG4C2s3iOTKlaUWxqytQmdPbxMG2aZ1vwkXJVrC7dheAA7TE"
    region: "RegionOne"





  # TODO(user): Add fields here
