apiVersion: ecns.easystack.com/v1
kind: Plan
metadata:
  labels:
    app.kubernetes.io/name: plan
    app.kubernetes.io/instance: plan-sample
    app.kubernetes.io/part-of: easystack-eks-op
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: easystack-eks-op
  name: plan-sample
  namespace: test-capo
spec:
  mode: "new"
  k8sVersion: "v1.26.4-es"
  support_python3: false
  lb_enable: false
  cluster_name: "test1"
  ssh_key: "binshan"
  use_float_ip: true
  node_cidr: "10.6.0.0/24"
  other_ansible_opts:
    "charts_repo_ip": "10.222.255.253"
    "cloud_master_vip": "172.35.0.2"
    "cloud_provider": "external"
    "container_lvm_enabled": "false"
    "data_dir": "/kubernetes"
    "dnscache_enabled": "true"
    "docker_repo_enabled": "false"
    "epel_enabled": "false"
    "etcd_data_dir": "/kubernetes/etcd"
    "flannel_interface": "ens3"
    "fs_server": "10.20.0.2"
    "fs_server_ip": ""
    "harbor_admin_password": "cY4EMha0EIpDA2cW"
    "harbor_domain": "hub.ecns.io"
    "helm_enabled": "true"
    "istio_enabled": "false"
    "keepalived_interface": "ens3"
    "kube_network_plugin": "flannel"
    "kubeadm_enabled": "false"
    "kubepods_reserve": "true"
    "openstack_auth_domain": "keystone.openstack.svc.cluster.local"
    "openstack_cinder_domain": "cinder.openstack.svc.cluster.local"
    "openstack_nova_domain": "nova.openstack.svc.cluster.local"
    "openstack_password": "test@passw3535rd"
    "openstack_project_domain_name": "Default"
    "openstack_project_name": "admin"
    "openstack_region_name": "RegionOne"
    "openstack_user_app_cred_name": "xxtest"
    "openstack_user_name": "admin"
    "populate_inventory_to_hosts_file": "false"
    "preinstall_selinux_state": "disabled"
    "registry_ip": "172.38.0.2"
    "upstream_nameservers": "114.114.114.114"
    "vip_mgmt": "192.168.23.2"
    "webhook_enabled": "false"
  need_keep_alive:
    - "master"
    - "ingress"
    - "ingress1"
  need_load_balancer:
    - "ingress"
    - "master"
    - "ingress1"
  machine_sets:
    - name: "test-master"
      role: "master"
      number: 3
      infras:
        - uid: "7d2d"
          availability_zone: "default-az"
          volumes:
            - volume_type: "hdd"
              volume_size: 150
              index: 1
            - volume_type: "hdd"
              volume_size: 10
              index: 2
            - volume_type: "hdd"
              volume_size: 5
              index: 3
          image: "kylin-x86-raw-0816"
          flavor: "8C-8G"
          replica: 2
        - uid: "7d3d"
          availability_zone: "default-az"
          volumes:
            - volume_type: "hdd"
              volume_size: 150
              index: 1
            - volume_type: "hdd"
              volume_size: 5
              index: 2
            - volume_type: "hdd"
              volume_size: 5
              index: 3
          image: "kylin-x86-raw-0816"
          flavor: "8C-8G"
          replica: 1
    - name: "test-node"
      number: 1
      role: "node"
      infras:
        - uid: "bb85"
          availability_zone: "default-az"
          volumes:
            - volume_type: "hdd"
              volume_size: 150
              index: 1
            - volume_type: "hdd"
              volume_size: 10
              index: 2
            - volume_type: "hdd"
              volume_size: 5
              index: 3
          image: "kylin-x86-raw-0816"
          flavor: "8C-8G"
          replica: 1
    - name: "test-ingress"
      number: 1
      role: "ingress"
      infras:
        - uid: "bb90"
          availability_zone: "default-az"
          volumes:
            - volume_type: "hdd"
              volume_size: 150
              index: 1
            - volume_type: "hdd"
              volume_size: 10
              index: 2
            - volume_type: "hdd"
              volume_size: 5
              index: 3
          image: "kylin-x86-raw-0816"
          flavor: "8C-8G"
          replica: 1
    - name: "test-ingress"
      number: 0
      role: "ingress1"
      infras:
        - uid: "bb95"
          availability_zone: "default-az"
          volumes:
            - volume_type: "hdd"
              volume_size: 150
              index: 1
            - volume_type: "hdd"
              volume_size: 10
              index: 2
            - volume_type: "hdd"
              volume_size: 5
              index: 3
          image: "kylin-x86-raw-0816"
          flavor: "8C-8G"
          replica: 0
    - name: "test-ingress"
      number: 0
      role: "ingress2"
      infras:
        - uid: "bb100"
          availability_zone: "default-az"
          volumes:
            - volume_type: "hdd"
              volume_size: 150
              index: 1
            - volume_type: "hdd"
              volume_size: 10
              index: 2
            - volume_type: "hdd"
              volume_size: 5
              index: 3
          image: "kylin-x86-raw-0816"
          flavor: "8C-8G"
          replica: 0
  monitor:
    pvc_type: "hdd"
    pvc_cap: "10"
    auto_clear_days: "7"
  cni_type: "flannel"
  pod_cidr: "10.232.0.0/14"
  svc_cidr: "10.222.0.0/16"
  ansible_plan_auto: false
  user:
    auth_url: "http://keystone.openstack.svc.cluster.local/v3"
    token: "gAAAAABk4s5ALnOdaflepp3c6R7mC8UKsyITGuQqq8QSjgpSiuQ8wP3rXgy71oduJ98v9TrOUAlEOqpFeTJjZJwsJin1hpnm_-jGps53Fuow7vgQgRJpnSUCLf9MmgBrAMWkqa151alCeeRaKLeuIpmBDjLoO2aOTrhiWqsnFbi7-60WnCvZQho"
    region: "RegionOne"





  # TODO(user): Add fields here
